apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web
        image: gcr.io/containers05-06/myfirstapp:3.0
        env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MESSAGE
          value: "ANTONIO JR. - LAB_GABY"
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
